name: Build Windows EXE

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-windows-exe:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~\AppData\Local\pip\Cache
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        shell: pwsh
        run: |
          python -m pip install --upgrade pip
          if (Test-Path 'requirements.txt') { pip install -r requirements.txt }
          if (Test-Path 'requirements-dev.txt') { pip install -r requirements-dev.txt }
          # Ensure PyInstaller is available if not pinned in requirements
          if (-not (python -c "import importlib, sys; sys.exit(0 if importlib.util.find_spec('PyInstaller') else 1)")) {
            pip install pyinstaller
          }

      - name: Build executable
        shell: pwsh
        run: |
          if (Test-Path 'build_exe.bat') {
            cmd.exe /c build_exe.bat
          }
          elseif (Test-Path 'app.spec') {
            pyinstaller -y app.spec
          }
          elseif (Test-Path 'app.py') {
            pyinstaller --clean --noconfirm --onefile app.py
          }
          else {
            Write-Error 'No build script, spec file, or app.py found to build.'
            exit 1
          }

      - name: Upload dist artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-exe-dist
          path: |
            dist/**
            build/**
          if-no-files-found: error
